-- Seed data for Food Assistance Directory
-- Run this after the migration to populate with sample data

INSERT INTO organizations (
  name, address, town, zip, contact_name, phone, email, website, facebook,
  assistance_types, who_served, cost, num_meals_available,
  operating_hours, hours_notes, donations_accepted, storage_capacity,
  comments, is_active, spanish_available
) VALUES
(
  'Beaufort Community Food Pantry',
  '123 Main Street',
  'Beaufort',
  '28516',
  'Mary Johnson',
  '2525551234',
  'contact@beaufortpantry.org',
  'https://beaufortpantry.org',
  'https://facebook.com/beaufortpantry',
  ARRAY['staffed_pantry', 'hot_meals_pickup'],
  ARRAY['all'],
  'free',
  100,
  '[{"day":"monday","open_time":"09:00","close_time":"17:00","is_closed":false},{"day":"tuesday","open_time":"09:00","close_time":"17:00","is_closed":false},{"day":"wednesday","open_time":"09:00","close_time":"17:00","is_closed":false},{"day":"thursday","open_time":"09:00","close_time":"17:00","is_closed":false},{"day":"friday","open_time":"09:00","close_time":"15:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  'Closed on major holidays',
  ARRAY['non_perishables', 'fresh_produce', 'frozen_meals_or_meats'],
  '{"refrigerator": true, "freezer": true, "dry_storage": true}'::jsonb,
  'Serving the community since 1995',
  true,
  true
),
(
  'Morehead City Meals on Wheels',
  '456 Atlantic Avenue',
  'Morehead City',
  '28557',
  'Robert Smith',
  '2525552345',
  'info@moreheadmeals.org',
  NULL,
  NULL,
  ARRAY['hot_meals_delivery'],
  ARRAY['older_adults'],
  'sliding_scale',
  75,
  '[{"day":"monday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"tuesday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"wednesday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"thursday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"friday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  NULL,
  ARRAY['prepared_meals', 'non_perishables'],
  '{"refrigerator": true, "freezer": false, "dry_storage": true}'::jsonb,
  'Home delivery available for seniors and homebound individuals',
  true,
  false
),
(
  'Newport Baptist Church Food Ministry',
  '789 Church Street',
  'Newport',
  '28570',
  'Pastor James Williams',
  '2525553456',
  'foodministry@newportbaptist.org',
  NULL,
  NULL,
  ARRAY['staffed_pantry', 'self_serve_pantry'],
  ARRAY['all'],
  'free',
  NULL,
  '[{"day":"monday","is_closed":true},{"day":"tuesday","open_time":"10:00","close_time":"12:00","is_closed":false},{"day":"wednesday","is_closed":true},{"day":"thursday","open_time":"10:00","close_time":"12:00","is_closed":false},{"day":"friday","is_closed":true},{"day":"saturday","open_time":"09:00","close_time":"11:00","is_closed":false},{"day":"sunday","is_closed":true}]'::jsonb,
  'Self-serve pantry available 24/7 at the church entrance',
  ARRAY['non_perishables', 'hygiene_or_housecleaning'],
  '{"refrigerator": false, "freezer": false, "dry_storage": true}'::jsonb,
  NULL,
  true,
  true
),
(
  'Emerald Isle Community Center Food Bank',
  '321 Coast Guard Road',
  'Emerald Isle',
  '28594',
  'Sarah Davis',
  '2525554567',
  NULL,
  'https://emeraldislecc.org/foodbank',
  NULL,
  ARRAY['staffed_pantry', 'collection'],
  ARRAY['all'],
  'free',
  NULL,
  '[{"day":"monday","open_time":"09:00","close_time":"16:00","is_closed":false},{"day":"tuesday","is_closed":true},{"day":"wednesday","open_time":"09:00","close_time":"16:00","is_closed":false},{"day":"thursday","is_closed":true},{"day":"friday","open_time":"09:00","close_time":"16:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  NULL,
  ARRAY['non_perishables', 'fresh_produce', 'clothing_or_shoes', 'kitchen_household_items'],
  '{"refrigerator": true, "freezer": true, "dry_storage": true}'::jsonb,
  'Also offers clothing assistance and household items',
  true,
  false
),
(
  'Havelock Family Services',
  '555 Main Street',
  'Havelock',
  '28532',
  'Linda Martinez',
  '2525555678',
  'help@havelockfamilyservices.org',
  NULL,
  NULL,
  ARRAY['staffed_pantry', 'hot_meals_pickup'],
  ARRAY['children', 'all'],
  'free',
  50,
  '[{"day":"monday","open_time":"08:00","close_time":"17:00","is_closed":false},{"day":"tuesday","open_time":"08:00","close_time":"17:00","is_closed":false},{"day":"wednesday","open_time":"08:00","close_time":"17:00","is_closed":false},{"day":"thursday","open_time":"08:00","close_time":"17:00","is_closed":false},{"day":"friday","open_time":"08:00","close_time":"15:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  'Extended hours during school holidays',
  ARRAY['non_perishables', 'fresh_produce', 'frozen_meals_or_meats', 'hygiene_or_housecleaning'],
  '{"refrigerator": true, "freezer": true, "dry_storage": true}'::jsonb,
  'Special programs for military families',
  true,
  true
),
(
  'Swansboro United Methodist Food Closet',
  '200 Main Street',
  'Swansboro',
  '28584',
  NULL,
  '2525556789',
  NULL,
  NULL,
  NULL,
  ARRAY['self_serve_pantry'],
  ARRAY['all'],
  'free',
  NULL,
  '[{"day":"monday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"tuesday","is_closed":true},{"day":"wednesday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"thursday","is_closed":true},{"day":"friday","open_time":"10:00","close_time":"14:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  NULL,
  ARRAY['non_perishables'],
  '{"refrigerator": false, "freezer": false, "dry_storage": true}'::jsonb,
  NULL,
  true,
  false
),
(
  'Down East Community Kitchen',
  '100 Harbor Road',
  'Harkers Island',
  '28531',
  'Tom Brown',
  '2525557890',
  'kitchen@downeastcommunity.org',
  NULL,
  NULL,
  ARRAY['hot_meals_pickup', 'hot_meals_delivery'],
  ARRAY['all'],
  'free',
  60,
  '[{"day":"monday","is_closed":true},{"day":"tuesday","open_time":"11:00","close_time":"13:00","is_closed":false},{"day":"wednesday","is_closed":true},{"day":"thursday","open_time":"11:00","close_time":"13:00","is_closed":false},{"day":"friday","is_closed":true},{"day":"saturday","open_time":"11:00","close_time":"13:00","is_closed":false},{"day":"sunday","is_closed":true}]'::jsonb,
  'Hot lunch served; delivery available for homebound residents',
  ARRAY['prepared_meals', 'fresh_produce', 'non_perishables'],
  '{"refrigerator": true, "freezer": true, "dry_storage": true}'::jsonb,
  'Community gathering place since 2010',
  true,
  false
),
(
  'Atlantic Beach Senior Center',
  '400 Atlantic Boulevard',
  'Atlantic Beach',
  '28512',
  'Betty Wilson',
  '2525558901',
  NULL,
  NULL,
  NULL,
  ARRAY['hot_meals_pickup'],
  ARRAY['older_adults'],
  'free',
  40,
  '[{"day":"monday","open_time":"11:30","close_time":"13:00","is_closed":false},{"day":"tuesday","open_time":"11:30","close_time":"13:00","is_closed":false},{"day":"wednesday","open_time":"11:30","close_time":"13:00","is_closed":false},{"day":"thursday","open_time":"11:30","close_time":"13:00","is_closed":false},{"day":"friday","open_time":"11:30","close_time":"13:00","is_closed":false},{"day":"saturday","is_closed":true},{"day":"sunday","is_closed":true}]'::jsonb,
  'Lunch service for seniors 60+',
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  false
);

-- Get organization IDs for volunteer needs (will need to update with actual IDs after insert)
-- Sample volunteer needs (run after organizations are inserted)
INSERT INTO volunteer_needs (organization_id, title, description, needed_date, needed_skills, time_commitment, is_active, contact_email)
SELECT
  id,
  'Food Pantry Volunteer',
  'Help sort and distribute food to community members. Great opportunity for families and groups!',
  '2024-02-01'::date,
  ARRAY['Physical ability to lift boxes', 'Friendly demeanor'],
  '3-4 hours per shift',
  true,
  'volunteer@beaufortpantry.org'
FROM organizations WHERE name = 'Beaufort Community Food Pantry';

INSERT INTO volunteer_needs (organization_id, title, description, needed_skills, time_commitment, is_active, contact_email)
SELECT
  id,
  'Meal Delivery Driver',
  'Deliver hot meals to homebound seniors in the Morehead City area. Must have valid drivers license and reliable vehicle.',
  ARRAY['Valid drivers license', 'Reliable vehicle', 'Compassionate personality'],
  '2-3 hours, weekday mornings',
  true,
  'volunteer@moreheadmeals.org'
FROM organizations WHERE name = 'Morehead City Meals on Wheels';

INSERT INTO volunteer_needs (organization_id, title, description, needed_date, needed_skills, time_commitment, is_active, contact_email)
SELECT
  id,
  'Weekend Kitchen Helper',
  'Assist with food preparation for our weekend meal programs. Experience not required!',
  '2024-01-27'::date,
  ARRAY['Ability to follow instructions', 'Food handling knowledge a plus'],
  '4 hours on Saturday mornings',
  true,
  'volunteer@havelockfamilyservices.org'
FROM organizations WHERE name = 'Havelock Family Services';
