import {
  Organization,
  VolunteerNeed,
  AssistanceType,
  DonationType,
  ServedPopulation,
  CostType,
  OperatingHours,
} from '@/types/database';

const createOperatingHours = (
  day: OperatingHours['day'],
  open_time?: string,
  close_time?: string,
  is_closed: boolean = false
): OperatingHours => ({
  day,
  open_time,
  close_time,
  is_closed,
});

export const sampleOrganizations: Organization[] = [
  {
    id: '1',
    name: 'Beaufort Community Food Pantry',
    address: '123 Main Street',
    town: 'Beaufort',
    zip: '28516',
    contact_name: 'Mary Johnson',
    phone: '2525551234',
    email: 'contact@beaufortpantry.org',
    website: 'https://beaufortpantry.org',
    facebook: 'https://facebook.com/beaufortpantry',
    assistance_types: ['staffed_pantry', 'hot_meals_pickup'] as AssistanceType[],
    who_served: ['all'] as ServedPopulation[],
    cost: 'free' as CostType,
    num_meals_available: 100,
    operating_hours: [
      createOperatingHours('monday', '09:00', '17:00'),
      createOperatingHours('tuesday', '09:00', '17:00'),
      createOperatingHours('wednesday', '09:00', '17:00'),
      createOperatingHours('thursday', '09:00', '17:00'),
      createOperatingHours('friday', '09:00', '15:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    hours_notes: 'Closed on major holidays',
    donations_accepted: ['non_perishables', 'fresh_produce', 'frozen_meals_or_meats'] as DonationType[],
    storage_capacity: { refrigerator: true, freezer: true, dry_storage: true },
    comments: 'Serving the community since 1995',
    last_updated: '2024-01-15T10:00:00Z',
    updated_by: 'admin',
    is_active: true,
    spanish_available: true,
    created_at: '2020-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Morehead City Meals on Wheels',
    address: '456 Atlantic Avenue',
    town: 'Morehead City',
    zip: '28557',
    contact_name: 'Robert Smith',
    phone: '2525552345',
    email: 'info@moreheadmeals.org',
    assistance_types: ['hot_meals_delivery'] as AssistanceType[],
    who_served: ['older_adults'] as ServedPopulation[],
    cost: 'sliding_scale' as CostType,
    num_meals_available: 75,
    operating_hours: [
      createOperatingHours('monday', '10:00', '14:00'),
      createOperatingHours('tuesday', '10:00', '14:00'),
      createOperatingHours('wednesday', '10:00', '14:00'),
      createOperatingHours('thursday', '10:00', '14:00'),
      createOperatingHours('friday', '10:00', '14:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    donations_accepted: ['prepared_meals', 'non_perishables'] as DonationType[],
    storage_capacity: { refrigerator: true, freezer: false, dry_storage: true },
    comments: 'Home delivery available for seniors and homebound individuals',
    last_updated: '2024-01-10T10:00:00Z',
    is_active: true,
    spanish_available: false,
    created_at: '2019-06-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Newport Baptist Church Food Ministry',
    address: '789 Church Street',
    town: 'Newport',
    zip: '28570',
    contact_name: 'Pastor James Williams',
    phone: '2525553456',
    email: 'foodministry@newportbaptist.org',
    assistance_types: ['staffed_pantry', 'self_serve_pantry'] as AssistanceType[],
    who_served: ['all'] as ServedPopulation[],
    cost: 'free' as CostType,
    operating_hours: [
      createOperatingHours('monday', undefined, undefined, true),
      createOperatingHours('tuesday', '10:00', '12:00'),
      createOperatingHours('wednesday', undefined, undefined, true),
      createOperatingHours('thursday', '10:00', '12:00'),
      createOperatingHours('friday', undefined, undefined, true),
      createOperatingHours('saturday', '09:00', '11:00'),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    hours_notes: 'Self-serve pantry available 24/7 at the church entrance',
    donations_accepted: ['non_perishables', 'hygiene_or_housecleaning'] as DonationType[],
    storage_capacity: { refrigerator: false, freezer: false, dry_storage: true },
    last_updated: '2024-01-12T10:00:00Z',
    is_active: true,
    spanish_available: true,
    created_at: '2018-03-15T00:00:00Z',
  },
  {
    id: '4',
    name: 'Emerald Isle Community Center Food Bank',
    address: '321 Coast Guard Road',
    town: 'Emerald Isle',
    zip: '28594',
    contact_name: 'Sarah Davis',
    phone: '2525554567',
    website: 'https://emeraldislecc.org/foodbank',
    assistance_types: ['staffed_pantry', 'collection'] as AssistanceType[],
    who_served: ['all'] as ServedPopulation[],
    cost: 'free' as CostType,
    operating_hours: [
      createOperatingHours('monday', '09:00', '16:00'),
      createOperatingHours('tuesday', undefined, undefined, true),
      createOperatingHours('wednesday', '09:00', '16:00'),
      createOperatingHours('thursday', undefined, undefined, true),
      createOperatingHours('friday', '09:00', '16:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    donations_accepted: ['non_perishables', 'fresh_produce', 'clothing_or_shoes', 'kitchen_household_items'] as DonationType[],
    storage_capacity: { refrigerator: true, freezer: true, dry_storage: true },
    comments: 'Also offers clothing assistance and household items',
    last_updated: '2024-01-08T10:00:00Z',
    is_active: true,
    spanish_available: false,
    created_at: '2017-09-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Havelock Family Services',
    address: '555 Main Street',
    town: 'Havelock',
    zip: '28532',
    contact_name: 'Linda Martinez',
    phone: '2525555678',
    email: 'help@havelockfamilyservices.org',
    assistance_types: ['staffed_pantry', 'hot_meals_pickup'] as AssistanceType[],
    who_served: ['children', 'all'] as ServedPopulation[],
    cost: 'free' as CostType,
    num_meals_available: 50,
    operating_hours: [
      createOperatingHours('monday', '08:00', '17:00'),
      createOperatingHours('tuesday', '08:00', '17:00'),
      createOperatingHours('wednesday', '08:00', '17:00'),
      createOperatingHours('thursday', '08:00', '17:00'),
      createOperatingHours('friday', '08:00', '15:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    hours_notes: 'Extended hours during school holidays',
    donations_accepted: ['non_perishables', 'fresh_produce', 'frozen_meals_or_meats', 'hygiene_or_housecleaning'] as DonationType[],
    storage_capacity: { refrigerator: true, freezer: true, dry_storage: true },
    comments: 'Special programs for military families',
    last_updated: '2024-01-14T10:00:00Z',
    is_active: true,
    spanish_available: true,
    created_at: '2016-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Swansboro United Methodist Food Closet',
    address: '200 Main Street',
    town: 'Swansboro',
    zip: '28584',
    phone: '2525556789',
    assistance_types: ['self_serve_pantry'] as AssistanceType[],
    who_served: ['all'] as ServedPopulation[],
    cost: 'free' as CostType,
    operating_hours: [
      createOperatingHours('monday', '10:00', '14:00'),
      createOperatingHours('tuesday', undefined, undefined, true),
      createOperatingHours('wednesday', '10:00', '14:00'),
      createOperatingHours('thursday', undefined, undefined, true),
      createOperatingHours('friday', '10:00', '14:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    donations_accepted: ['non_perishables'] as DonationType[],
    storage_capacity: { refrigerator: false, freezer: false, dry_storage: true },
    last_updated: '2024-01-05T10:00:00Z',
    is_active: true,
    spanish_available: false,
    created_at: '2015-06-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Down East Community Kitchen',
    address: '100 Harbor Road',
    town: 'Harkers Island',
    zip: '28531',
    contact_name: 'Tom Brown',
    phone: '2525557890',
    email: 'kitchen@downeastcommunity.org',
    assistance_types: ['hot_meals_pickup', 'hot_meals_delivery'] as AssistanceType[],
    who_served: ['all'] as ServedPopulation[],
    cost: 'free' as CostType,
    num_meals_available: 60,
    operating_hours: [
      createOperatingHours('monday', undefined, undefined, true),
      createOperatingHours('tuesday', '11:00', '13:00'),
      createOperatingHours('wednesday', undefined, undefined, true),
      createOperatingHours('thursday', '11:00', '13:00'),
      createOperatingHours('friday', undefined, undefined, true),
      createOperatingHours('saturday', '11:00', '13:00'),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    hours_notes: 'Hot lunch served; delivery available for homebound residents',
    donations_accepted: ['prepared_meals', 'fresh_produce', 'non_perishables'] as DonationType[],
    storage_capacity: { refrigerator: true, freezer: true, dry_storage: true },
    comments: 'Community gathering place since 2010',
    last_updated: '2024-01-11T10:00:00Z',
    is_active: true,
    spanish_available: false,
    created_at: '2010-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Atlantic Beach Senior Center',
    address: '400 Atlantic Boulevard',
    town: 'Atlantic Beach',
    zip: '28512',
    contact_name: 'Betty Wilson',
    phone: '2525558901',
    assistance_types: ['hot_meals_pickup'] as AssistanceType[],
    who_served: ['older_adults'] as ServedPopulation[],
    cost: 'free' as CostType,
    num_meals_available: 40,
    operating_hours: [
      createOperatingHours('monday', '11:30', '13:00'),
      createOperatingHours('tuesday', '11:30', '13:00'),
      createOperatingHours('wednesday', '11:30', '13:00'),
      createOperatingHours('thursday', '11:30', '13:00'),
      createOperatingHours('friday', '11:30', '13:00'),
      createOperatingHours('saturday', undefined, undefined, true),
      createOperatingHours('sunday', undefined, undefined, true),
    ],
    hours_notes: 'Lunch service for seniors 60+',
    donations_accepted: [] as DonationType[],
    last_updated: '2024-01-09T10:00:00Z',
    is_active: true,
    spanish_available: false,
    created_at: '2012-05-01T00:00:00Z',
  },
];

export const sampleVolunteerNeeds: VolunteerNeed[] = [
  {
    id: '1',
    organization_id: '1',
    title: 'Food Pantry Volunteer',
    description: 'Help sort and distribute food to community members. Great opportunity for families and groups!',
    needed_date: '2024-02-01',
    needed_skills: ['Physical ability to lift boxes', 'Friendly demeanor'],
    time_commitment: '3-4 hours per shift',
    is_active: true,
    posted_date: '2024-01-15T10:00:00Z',
    contact_email: 'volunteer@beaufortpantry.org',
  },
  {
    id: '2',
    organization_id: '2',
    title: 'Meal Delivery Driver',
    description: 'Deliver hot meals to homebound seniors in the Morehead City area. Must have valid drivers license and reliable vehicle.',
    needed_skills: ['Valid drivers license', 'Reliable vehicle', 'Compassionate personality'],
    time_commitment: '2-3 hours, weekday mornings',
    is_active: true,
    posted_date: '2024-01-10T10:00:00Z',
    contact_email: 'volunteer@moreheadmeals.org',
  },
  {
    id: '3',
    organization_id: '5',
    title: 'Weekend Kitchen Helper',
    description: 'Assist with food preparation for our weekend meal programs. Experience not required!',
    needed_date: '2024-01-27',
    needed_skills: ['Ability to follow instructions', 'Food handling knowledge a plus'],
    time_commitment: '4 hours on Saturday mornings',
    is_active: true,
    posted_date: '2024-01-14T10:00:00Z',
    contact_email: 'volunteer@havelockfamilyservices.org',
  },
];

export function getSampleTowns(): string[] {
  return [...new Set(sampleOrganizations.map((org) => org.town))].sort();
}
